"""add dependency permissions and all_stacks flag to team_permissions

Revision ID: 44c7ee145272
Revises: c0cba37890a4
Create Date: 2025-12-29 20:33:37.004470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c7ee145272'
down_revision: Union[str, Sequence[str], None] = 'c0cba37890a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_permissions', sa.Column('all_stacks', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('team_permissions', sa.Column('can_view_dependencies', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('team_permissions', sa.Column('can_plan_dependencies', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('team_permissions', sa.Column('can_apply_dependencies', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_permissions', 'can_apply_dependencies')
    op.drop_column('team_permissions', 'can_plan_dependencies')
    op.drop_column('team_permissions', 'can_view_dependencies')
    op.drop_column('team_permissions', 'all_stacks')
    # ### end Alembic commands ###
