"""Add stack_id and depends_on to stacks table

Revision ID: 6b8cec360c6e
Revises: b45176432f16
Create Date: 2025-12-26 18:42:08.862409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8cec360c6e'
down_revision: Union[str, Sequence[str], None] = 'b45176432f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stacks', sa.Column('stack_id', sa.String(length=255), nullable=True))
    op.add_column('stacks', sa.Column('depends_on', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_stacks_stack_id'), 'stacks', ['stack_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stacks_stack_id'), table_name='stacks')
    op.drop_column('stacks', 'depends_on')
    op.drop_column('stacks', 'stack_id')
    # ### end Alembic commands ###
