"""add_backend_storage_id_to_environments

Revision ID: b78b28cf80ee
Revises: d63bd8611052
Create Date: 2026-01-08 16:07:19.492395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78b28cf80ee'
down_revision: Union[str, Sequence[str], None] = 'd63bd8611052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the new column and index, skip the foreign key constraints that SQLite doesn't support
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backend_storage_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_environments_backend_storage_id'), ['backend_storage_id'], unique=False)
        batch_op.create_foreign_key('fk_environments_backend_storage', 'backend_storages', ['backend_storage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_environments_backend_storage', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_environments_backend_storage_id'))
        batch_op.drop_column('backend_storage_id')
    # ### end Alembic commands ###
