"""add_backend_storage_id_to_environments

Revision ID: b78b28cf80ee
Revises: d63bd8611052
Create Date: 2026-01-08 16:07:19.492395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78b28cf80ee'
down_revision: Union[str, Sequence[str], None] = 'd63bd8611052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'context_env_vars', type_='foreignkey')
    op.create_foreign_key(None, 'context_env_vars', 'contexts', ['context_id'], ['id'])
    op.drop_constraint(None, 'context_secrets', type_='foreignkey')
    op.create_foreign_key(None, 'context_secrets', 'contexts', ['context_id'], ['id'])
    op.drop_constraint(None, 'contexts', type_='foreignkey')
    op.create_foreign_key(None, 'contexts', 'projects', ['project_id'], ['id'])
    op.add_column('environments', sa.Column('backend_storage_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_environments_backend_storage_id'), 'environments', ['backend_storage_id'], unique=False)
    op.create_foreign_key(None, 'environments', 'backend_storages', ['backend_storage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.drop_index(op.f('ix_environments_backend_storage_id'), table_name='environments')
    op.drop_column('environments', 'backend_storage_id')
    op.drop_constraint(None, 'contexts', type_='foreignkey')
    op.create_foreign_key(None, 'contexts', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'context_secrets', type_='foreignkey')
    op.create_foreign_key(None, 'context_secrets', 'contexts', ['context_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'context_env_vars', type_='foreignkey')
    op.create_foreign_key(None, 'context_env_vars', 'contexts', ['context_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
