"""add contexts and context_secrets tables

Revision ID: d5f9a8b3c4e2
Revises: c0cba37890a4
Create Date: 2025-12-30 20:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f9a8b3c4e2'
down_revision: Union[str, Sequence[str], None] = 'c0cba37890a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contexts_name'), 'contexts', ['name'], unique=False)
    op.create_index(op.f('ix_contexts_project_id'), 'contexts', ['project_id'], unique=False)
    
    op.create_table('context_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('vault_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_secrets_context_id'), 'context_secrets', ['context_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_secrets_context_id'), table_name='context_secrets')
    op.drop_table('context_secrets')
    op.drop_index(op.f('ix_contexts_project_id'), table_name='contexts')
    op.drop_index(op.f('ix_contexts_name'), table_name='contexts')
    op.drop_table('contexts')
    # ### end Alembic commands ###
