"""add env_var_name to context_secrets

Revision ID: f8c3d4e2a1b9
Revises: e7a9c2b5d3f1
Create Date: 2026-01-01 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c3d4e2a1b9'
down_revision: Union[str, Sequence[str], None] = 'e7a9c2b5d3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add env_var_name column to context_secrets table
    # Using SQLAlchemy operations for SQLite compatibility
    with op.batch_alter_table('context_secrets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('env_var_name', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context_secrets', 'env_var_name')
    # ### end Alembic commands ###
