"""add env_var_name to context_secrets

Revision ID: f8c3d4e2a1b9
Revises: e7a9c2b5d3f1
Create Date: 2026-01-01 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c3d4e2a1b9'
down_revision: Union[str, Sequence[str], None] = 'e7a9c2b5d3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the column already exists before adding it (for idempotency)
    # Add env_var_name column to context_secrets table
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_name='context_secrets' 
                AND column_name='env_var_name'
            ) THEN
                ALTER TABLE context_secrets 
                ADD COLUMN env_var_name VARCHAR(255) DEFAULT '' NOT NULL;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context_secrets', 'env_var_name')
    # ### end Alembic commands ###
